name: Pipeline CI/CD
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  job1:
    name: build_ecr
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./repositorio-aplicacao # <--- CRUCIAL PARA ENCONTRAR O DOCKERFILE
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::124355678962:role/GitHubActionsRepoApp
          aws-region: us-east-1
      
      - name: Amazon ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        run: |
          docker build -t meu-website:v1.0 .
          docker tag meu-website:v1.0 124355678962.dkr.ecr.us-east-1.amazonaws.com/site_prod:v1.0
          docker push 124355678962.dkr.ecr.us-east-1.amazonaws.com/site_prod:v1.0

  job2:
    name: deploy_ec2
    needs: job1
    runs-on: ubuntu-latest 
    steps:
      - name: Deploy via SSH
        env:
          PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
          INSTANCE_KEY: ${{ secrets.INSTANCE_KEY }}
        run: |
          echo "$INSTANCE_KEY" > chave.pem
          chmod 400 chave.pem
          ssh -i chave.pem -o StrictHostKeyChecking=no ec2-user@$PUBLIC_IP << EOF
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 124355678962.dkr.ecr.us-east-1.amazonaws.com
            docker pull 124355678962.dkr.ecr.us-east-1.amazonaws.com/site_prod:v1.0
            docker stop site || true
            docker rm site || true
            docker run -d -p 80:80 --name site 124355678962.dkr.ecr.us-east-1.amazonaws.com/site_prod:v1.0
          EOF
