name: Terraform CI/CD
on:
  workflow_dispatch:
    inputs: 
      apply:
        description: 'Executar o Terraform apply?'
        required: true
        default: 'false'
        type: choice
        options: [true, false]
      destroy:
        description: 'Destruir o ambiente?'
        required: true
        default: 'false'
        type: choice
        options: [true, false]

permissions:
  contents: read
  id-token: write

jobs:
  job1:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra-as-code # <--- CRUCIAL PARA MONOREPO
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::124355678962:role/GitHubinfraRole
          aws-region: us-east-1

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan.tfout

      - name: Terraform Apply
        if: github.event.inputs.apply == 'true' 
        run: terraform apply -auto-approve tfplan.tfout
